import './globals.css'
import Navigation from '@/components/navigation/navigation.component'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
